### PR TITLE
Make installation work for the RPi 1

### PR DESCRIPTION
**Pull request by claudiobizzotto**
* Convert install script from sh to bash
* Make install script behave according to RPi version: for RPi 1,
  some flags have to be changed/removed when compiling CJDNS

### CODE REVIEW

**Comment by claudiobizzotto** [comment]
**Before merging:** I've tested this on an Pi 1 and an Pi 3 today - would be nice to have someone test it on an Pi 2 as well.

**Comment by garrying** [comment]
@claudiobizzotto Tested on my Pi 1 and it looks good. @benhylau has a Pi 2 to test with.

**Comment by claudiobizzotto** [comment]
Thanks, @garrying :+1:

**Comment by benhylau** [comment]
Code looks good. Will test on Pi 2 and 3 and do benchmarks to make sure `CFLAGS` are passed properly. Weekend :)

**Pull request merged**
