### PR TITLE
Add example for adding ssh file

### PR DESCRIPTION
**Pull request by dcwalk**
Came up at virtual mesh that this step is confusing unless you've done it before. I agree!

### CODE REVIEW

**Comment by benhylau** [comment]
Not from Windows though right?

**Comment by dcwalk** [comment]
Yeah, but i figured that would at least provide some context similar to the other examples?
`wget` doesn't work on Windows without an install. And we now have [bash on windows 10](http://www.windowscentral.com/how-install-bash-shell-command-line-windows-10)

**Comment by benhylau** [comment]
Yes but all the commands like `wget` are run on the Pi. The `touch ssh` is not.

**Comment by dcwalk** [comment]
Your call! I'm fine to leave, I thought just demonstrating something might be helpful? Could specify from linux?

**Pull request merged**
